!!python/object/apply:pandas._libs.indexing.__pyx_unpickle_NDFrameIndexerBase
args:
- !!python/name:pandas.core.indexing._iLocIndexer ''
- 68575658
- null
state: !!python/tuple
- -1
- iloc
- !!python/object:pandas.core.frame.DataFrame
  _flags:
    allows_duplicate_labels: true
  _metadata: []
  _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
  - !!python/tuple
    - !!python/object/apply:pandas._libs.internals._unpickle_block
      - !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - &id001 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
          - 2
        - &id002 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          AAAAAAAA8D8AAAAAAADgPw==
      - !!python/object/apply:builtins.slice
        - 0
        - 1
        - 1
      - 2
    - !!python/object/apply:pandas._libs.internals._unpickle_block
      - !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
          - 2
        - !!python/object/apply:numpy.dtype
          args:
          - i4
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          AQAAAAEAAAA=
      - !!python/object/apply:builtins.slice
        - 1
        - 2
        - 1
      - 2
    - !!python/object/apply:pandas._libs.internals._unpickle_block
      - !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
          - 2
        - *id002
        - false
        - !!binary |
          exSuR+F6hD97FK5H4XqEPw==
      - !!python/object/apply:builtins.slice
        - 2
        - 3
        - 1
      - 2
    - !!python/object/apply:pandas._libs.internals._unpickle_block
      - !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
          - 2
        - !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          AQAAAAAAAAABAAAAAAAAAA==
      - !!python/object/apply:builtins.slice
        - 3
        - 4
        - 1
      - 2
  - - !!python/object/apply:pandas.core.indexes.base._new_Index
      - !!python/name:pandas.core.indexes.base.Index ''
      - data: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple
            - 0
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple
            - 4
          - !!python/object/apply:numpy.dtype
            args:
            - O8
            - false
            - true
            state: !!python/tuple
            - 3
            - '|'
            - null
            - null
            - null
            - -1
            - -1
            - 63
          - false
          - - constraint_center
            - constraint_width
            - learning_rate
            - n_epochs
        name: null
    - !!python/object/apply:pandas.core.indexes.base._new_Index
      - !!python/name:pandas.core.indexes.range.RangeIndex ''
      - name: null
        start: 0
        step: 1
        stop: 2
  _typ: dataframe
  attrs: {}
- axis: 0
