- - 1.0
  - 0.0
- - 1.0
  - 0.0
- - 1.0
  - 0.0
- - 0.0
  - 1.0
- - 0.0
  - 1.0
- - 1.0
  - 0.0
- - 0.0
  - 1.0
- - 0.0
  - 1.0
<<<<<<< Updated upstream
=======
- - 1.0
  - 0.0
- - 1.0
  - 0.0
>>>>>>> Stashed changes
- - 1.0
  - 0.0
